server:
  port: 19011

spring:
  application:
    name: mySelectShop
  datasource:
    url: jdbc:postgresql://localhost:5432/sparta
    username: sparta
    password: sparta
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true